// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Request
	Response
	RelayRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_UNKNOWN MsgType = 0
	MsgType_TEXT    MsgType = 1
	MsgType_JSON    MsgType = 2
	MsgType_BINARY  MsgType = 3
)

var MsgType_name = map[int32]string{
	0: "UNKNOWN",
	1: "TEXT",
	2: "JSON",
	3: "BINARY",
}
var MsgType_value = map[string]int32{
	"UNKNOWN": 0,
	"TEXT":    1,
	"JSON":    2,
	"BINARY":  3,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Request_RequestType int32

const (
	Request_RELAY Request_RequestType = 0
	Request_ID    Request_RequestType = 1
	Request_LIST  Request_RequestType = 2
)

var Request_RequestType_name = map[int32]string{
	0: "RELAY",
	1: "ID",
	2: "LIST",
}
var Request_RequestType_value = map[string]int32{
	"RELAY": 0,
	"ID":    1,
	"LIST":  2,
}

func (x Request_RequestType) String() string {
	return proto.EnumName(Request_RequestType_name, int32(x))
}
func (Request_RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Request struct {
	RequestType  Request_RequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,enum=pb.Request_RequestType" json:"request_type,omitempty"`
	RelayRequest *RelayRequest       `protobuf:"bytes,2,opt,name=relay_request,json=relayRequest" json:"relay_request,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetRequestType() Request_RequestType {
	if m != nil {
		return m.RequestType
	}
	return Request_RELAY
}

func (m *Request) GetRelayRequest() *RelayRequest {
	if m != nil {
		return m.RelayRequest
	}
	return nil
}

type Response struct {
	From    uint64  `protobuf:"varint,1,opt,name=from" json:"from,omitempty"`
	MsgType MsgType `protobuf:"varint,2,opt,name=msg_type,json=msgType,enum=pb.MsgType" json:"msg_type,omitempty"`
	Msg     []byte  `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetFrom() uint64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *Response) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_UNKNOWN
}

func (m *Response) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type RelayRequest struct {
	UserIds []uint64 `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds" json:"user_ids,omitempty"`
	MsgType MsgType  `protobuf:"varint,2,opt,name=msg_type,json=msgType,enum=pb.MsgType" json:"msg_type,omitempty"`
	Msg     []byte   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (m *RelayRequest) Reset()                    { *m = RelayRequest{} }
func (m *RelayRequest) String() string            { return proto.CompactTextString(m) }
func (*RelayRequest) ProtoMessage()               {}
func (*RelayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RelayRequest) GetUserIds() []uint64 {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func (m *RelayRequest) GetMsgType() MsgType {
	if m != nil {
		return m.MsgType
	}
	return MsgType_UNKNOWN
}

func (m *RelayRequest) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*RelayRequest)(nil), "pb.RelayRequest")
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("pb.Request_RequestType", Request_RequestType_name, Request_RequestType_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x3f, 0x4f, 0xf3, 0x30,
	0x10, 0x87, 0x6b, 0x27, 0x6f, 0x93, 0xf7, 0x92, 0x22, 0xeb, 0x16, 0xc2, 0x16, 0x65, 0x40, 0x51,
	0x87, 0x0e, 0x45, 0x30, 0xb0, 0x15, 0xd1, 0x21, 0x50, 0x52, 0xc9, 0x0d, 0xa2, 0x9d, 0xaa, 0x84,
	0x9a, 0x08, 0xa9, 0x21, 0xc6, 0x4e, 0x87, 0x7c, 0x23, 0x3e, 0x26, 0xca, 0x1f, 0x44, 0x66, 0x26,
	0x3f, 0x3f, 0xeb, 0xce, 0xf7, 0x9c, 0x0c, 0x93, 0x42, 0x68, 0x9d, 0xe6, 0x62, 0x26, 0x55, 0x59,
	0x95, 0x48, 0x65, 0x16, 0x7c, 0x11, 0xb0, 0xb8, 0xf8, 0x3c, 0x09, 0x5d, 0xe1, 0x2d, 0xb8, 0xaa,
	0xc3, 0x7d, 0x55, 0x4b, 0xe1, 0x11, 0x9f, 0x84, 0x67, 0xf3, 0xf3, 0x99, 0xcc, 0x66, 0x7d, 0xc9,
	0xcf, 0x99, 0xd4, 0x52, 0x70, 0x47, 0xfd, 0x06, 0xbc, 0x86, 0x89, 0x12, 0xc7, 0xb4, 0xde, 0xf7,
	0x97, 0x1e, 0xf5, 0x49, 0xe8, 0xcc, 0x59, 0xd7, 0x7c, 0x4c, 0xeb, 0xbe, 0x93, 0xbb, 0x6a, 0x90,
	0x82, 0x29, 0x38, 0x83, 0x27, 0xf1, 0x3f, 0xfc, 0xe3, 0xcb, 0xd5, 0x62, 0xc7, 0x46, 0x38, 0x06,
	0x1a, 0xdd, 0x33, 0x82, 0x36, 0x98, 0xab, 0x68, 0x93, 0x30, 0x1a, 0x6c, 0xc1, 0xe6, 0x42, 0xcb,
	0xf2, 0x43, 0x0b, 0x44, 0x30, 0xdf, 0x54, 0x59, 0xb4, 0x8a, 0x26, 0x6f, 0x19, 0x2f, 0xc1, 0x2e,
	0x74, 0xde, 0xa9, 0xd3, 0x56, 0xdd, 0x69, 0xa6, 0x3f, 0xe9, 0xbc, 0xd5, 0xb5, 0x8a, 0x0e, 0x90,
	0x81, 0x51, 0xe8, 0xdc, 0x33, 0x7c, 0x12, 0xba, 0xbc, 0xc1, 0xe0, 0x15, 0xdc, 0xa1, 0x23, 0x5e,
	0x80, 0x7d, 0xd2, 0x42, 0xed, 0xdf, 0x0f, 0xda, 0x23, 0xbe, 0x11, 0x9a, 0xdc, 0x6a, 0x72, 0x74,
	0xd0, 0x7f, 0x1f, 0x32, 0xbd, 0x01, 0xab, 0xaf, 0x42, 0x07, 0xac, 0xe7, 0xf8, 0x31, 0x5e, 0xbf,
	0xc4, 0x6c, 0xd4, 0x2c, 0x98, 0x2c, 0xb7, 0x49, 0xb7, 0xea, 0xc3, 0x66, 0x1d, 0x33, 0x8a, 0x00,
	0xe3, 0xbb, 0x28, 0x5e, 0xf0, 0x1d, 0x33, 0xb2, 0x71, 0xfb, 0x59, 0x57, 0xdf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xff, 0x2c, 0x76, 0x47, 0xbd, 0x01, 0x00, 0x00,
}
